import{render,waitFor}from"@testing-library/react";import{afterEach,beforeEach,describe,expect,it}from"vitest";import{TextEffectsEpicWin}from"../components/base/text-effects/css/TextEffectsEpicWin";describe("TextEffectsEpicWin",()=>{beforeEach(()=>{// Reset any animations between tests
document.body.innerHTML=""});afterEach(()=>{document.body.innerHTML=""});describe("Rendering",()=>{it("should render with default text \"EPIC WIN\"",()=>{const{container}=render(<TextEffectsEpicWin/>);const mainText=container.querySelector(".tfe-epic-win__main-text");expect(mainText).toBeTruthy();// textContent will have non-breaking spaces for regular spaces
expect(mainText?.textContent).toBe("EPIC\xA0WIN")});it("should render with custom text",()=>{const customText="LEVEL COMPLETE";const{container}=render(<TextEffectsEpicWin text={customText}/>);const mainText=container.querySelector(".tfe-epic-win__main-text");// textContent will have non-breaking spaces for regular spaces
expect(mainText?.textContent).toBe("LEVEL\xA0COMPLETE")});it("should render text with whitespace correctly",()=>{const textWithSpaces="YOU WIN!";const{container}=render(<TextEffectsEpicWin text={textWithSpaces}/>);const mainText=container.querySelector(".tfe-epic-win__main-text");// Non-breaking space (\u00A0) is used for spaces
expect(mainText).toBeTruthy();expect(mainText?.textContent).toContain("YOU");expect(mainText?.textContent).toContain("WIN!")});it("should render animation container with correct data attribute",()=>{const{container}=render(<TextEffectsEpicWin/>);const animationContainer=container.querySelector("[data-animation-id=\"text-effects__epic-win\"]");expect(animationContainer).toBeTruthy();expect(animationContainer?.className).toContain("tfe-epic-win")})});describe("Structure",()=>{it("should render all required shadow layers",()=>{const{container}=render(<TextEffectsEpicWin/>);const shadowFar=container.querySelector(".tfe-epic-win__shadow-far");const shadowMid=container.querySelector(".tfe-epic-win__shadow-mid");expect(shadowFar).toBeTruthy();expect(shadowMid).toBeTruthy();expect(shadowFar?.textContent).toBe("EPIC WIN");expect(shadowMid?.textContent).toBe("EPIC WIN")});it("should render individual character spans",()=>{const text="WIN";const{container}=render(<TextEffectsEpicWin text={text}/>);const chars=container.querySelectorAll(".tfe-epic-win__char");expect(chars.length).toBe(text.length)});it("should apply --char-index CSS variable to each character",()=>{const text="ABC";const{container}=render(<TextEffectsEpicWin text={text}/>);const chars=container.querySelectorAll(".tfe-epic-win__char");chars.forEach((char,index)=>{const style=(char as HTMLElement).style;expect(style.getPropertyValue("--char-index")).toBe(String(index))})});it("should render character inner wrapper with gradient",()=>{const{container}=render(<TextEffectsEpicWin text="A"/>);const charInner=container.querySelector(".tfe-epic-win__char-inner");expect(charInner).toBeTruthy()});it("should render character glow element for each character",()=>{const text="WIN";const{container}=render(<TextEffectsEpicWin text={text}/>);const glows=container.querySelectorAll(".tfe-epic-win__char-glow");expect(glows.length).toBe(text.length)})});describe("CSS Animation Classes",()=>{it("should apply animation class after mount",async()=>{const{container}=render(<TextEffectsEpicWin/>);const animationContainer=container.querySelector(".tfe-epic-win");// Animation class should be added after useEffect runs
await waitFor(()=>{expect(animationContainer?.classList.contains("tfe-epic-win--animate")).toBe(true)},{timeout:100})});it("should have proper class namespace to avoid conflicts",()=>{const{container}=render(<TextEffectsEpicWin/>);// All classes should be namespaced with tfe-epic-win-
const allElements=container.querySelectorAll("[class*=\"epic\"]");allElements.forEach(element=>{const classes=element.className.split(" ");classes.forEach(cls=>{if(cls.includes("epic")){expect(cls).toMatch(/^tfe-epic-win/)}})})})});describe("Accessibility",()=>{it("should render text content that is readable by screen readers",()=>{const text="CONGRATULATIONS";const{container}=render(<TextEffectsEpicWin text={text}/>);// Text appears in multiple places (shadows + main), check main text specifically
const mainText=container.querySelector(".tfe-epic-win__main-text");expect(mainText?.textContent).toBe(text)});it("should handle special characters correctly",()=>{const text="W!N";const{container}=render(<TextEffectsEpicWin text={text}/>);const mainText=container.querySelector(".tfe-epic-win__main-text");expect(mainText?.textContent).toBe(text)})});describe("Performance",()=>{it("should use memo to prevent unnecessary re-renders",()=>{const{rerender,container}=render(<TextEffectsEpicWin text="WIN"/>);const firstRender=container.querySelector(".tfe-epic-win");// Re-render with same props
rerender(<TextEffectsEpicWin text="WIN"/>);const secondRender=container.querySelector(".tfe-epic-win");// Component should be memoized (same props = no re-render needed)
expect(firstRender).toBeTruthy();expect(secondRender).toBeTruthy()});it("should re-render when text prop changes",()=>{const{rerender,container}=render(<TextEffectsEpicWin text="WIN"/>);const firstText=container.querySelector(".tfe-epic-win__main-text")?.textContent;rerender(<TextEffectsEpicWin text="LOSE"/>);const secondText=container.querySelector(".tfe-epic-win__main-text")?.textContent;expect(firstText).toBe("WIN");expect(secondText).toBe("LOSE")})});describe("Edge Cases",()=>{it("should handle empty string",()=>{const{container}=render(<TextEffectsEpicWin text=""/>);const mainText=container.querySelector(".tfe-epic-win__main-text");expect(mainText).toBeTruthy();expect(mainText?.children.length).toBe(0)});it("should handle single character",()=>{const{container}=render(<TextEffectsEpicWin text="A"/>);const chars=container.querySelectorAll(".tfe-epic-win__char");expect(chars.length).toBe(1)});it("should handle very long text",()=>{const longText="A".repeat(100);const{container}=render(<TextEffectsEpicWin text={longText}/>);const chars=container.querySelectorAll(".tfe-epic-win__char");expect(chars.length).toBe(100);// Each character should have unique index
const lastChar=chars[99]as HTMLElement;expect(lastChar.style.getPropertyValue("--char-index")).toBe("99")});it("should handle text with only spaces",()=>{const{container}=render(<TextEffectsEpicWin text="   "/>);const chars=container.querySelectorAll(".tfe-epic-win__char");expect(chars.length).toBe(3);// All spaces should be converted to non-breaking spaces
chars.forEach(char=>{const innerText=char.querySelector(".tfe-epic-win__char-inner")?.textContent;expect(innerText).toBe("\xA0")})});it("should handle mixed alphanumeric and special characters",()=>{const text="L3V3L 100!";const{container}=render(<TextEffectsEpicWin text={text}/>);const mainText=container.querySelector(".tfe-epic-win__main-text");// textContent will have non-breaking spaces for regular spaces
expect(mainText?.textContent).toBe("L3V3L\xA0100!")})});describe("CSS Integration",()=>{it("should import CSS file",()=>{// This test ensures the CSS import doesn't throw
expect(()=>{render(<TextEffectsEpicWin/>)}).not.toThrow()});it("should have proper container structure for CSS animations",()=>{const{container}=render(<TextEffectsEpicWin/>);const mainContainer=container.querySelector(".tfe-epic-win");const textContainer=container.querySelector(".tfe-epic-win__text-container");const mainText=container.querySelector(".tfe-epic-win__main-text");expect(mainContainer).toBeTruthy();expect(textContainer).toBeTruthy();expect(mainText).toBeTruthy();// Text container should be child of main container
expect(mainContainer?.contains(textContainer as Node)).toBe(true);expect(textContainer?.contains(mainText as Node)).toBe(true)})})});
