import{render}from"@testing-library/react";import{describe,expect,it}from"vitest";import{TextEffectsComboCounter}from"../components/base/text-effects/css/TextEffectsComboCounter";describe("TextEffectsComboCounter",()=>{describe("Generic Functionality",()=>{it("renders with default finalValue of 25",()=>{const{container}=render(<TextEffectsComboCounter/>);expect(container.querySelector(".tfx-combo-container")).toBeTruthy();expect(container.querySelector(".tfx-combo-digit")).toBeTruthy()});it("accepts custom finalValue prop",()=>{const{container}=render(<TextEffectsComboCounter finalValue={100}/>);expect(container.querySelector(".tfx-combo-container")).toBeTruthy()});it("accepts custom maxParticles prop",()=>{const{container}=render(<TextEffectsComboCounter finalValue={50}maxParticles={6}/>);const particles=container.querySelectorAll(".tfx-combo-particle");// Should have up to 6 particles but limited by finalValue/2
expect(particles.length).toBeGreaterThan(0);expect(particles.length).toBeLessThanOrEqual(6)});it("renders appropriate particle count for small finalValue",()=>{const{container}=render(<TextEffectsComboCounter finalValue={5}maxParticles={4}/>);const particles=container.querySelectorAll(".tfx-combo-particle");// finalValue=5 should show 2 particles (Math.floor(5/2))
expect(particles.length).toBe(2)});it("renders appropriate particle count for medium finalValue",()=>{const{container}=render(<TextEffectsComboCounter finalValue={25}maxParticles={4}/>);const particles=container.querySelectorAll(".tfx-combo-particle");// finalValue=25 should show 4 particles (min of maxParticles and floor(25/2))
expect(particles.length).toBe(4)});it("renders appropriate particle count for large finalValue",()=>{const{container}=render(<TextEffectsComboCounter finalValue={1000}maxParticles={4}/>);const particles=container.querySelectorAll(".tfx-combo-particle");// finalValue=1000 should be capped at maxParticles (4)
expect(particles.length).toBe(4)});it("shows incrementing particle values",()=>{const{container}=render(<TextEffectsComboCounter finalValue={100}maxParticles={4}/>);const particles=container.querySelectorAll(".tfx-combo-particle");// Check that particles show meaningful increments (not +1, +1, +1)
const values=Array.from(particles).map(p=>parseInt(p.textContent?.replace("+","")||"0"));values.forEach(value=>{expect(value).toBeGreaterThan(0)});// Sum of all increments should equal finalValue
const sum=values.reduce((acc,val)=>acc+val,0);expect(sum).toBe(100)});it("renders COMBO text letters",()=>{const{container}=render(<TextEffectsComboCounter/>);const letters=container.querySelectorAll(".tfx-combo-letter");expect(letters.length).toBe(5);// C-O-M-B-O
});it("renders hit marker",()=>{const{container}=render(<TextEffectsComboCounter/>);const hitMarker=container.querySelector(".tfx-combo-hit-marker");expect(hitMarker).toBeTruthy();expect(hitMarker?.textContent).toBe("\xD7")});it("renders perfect bonus text",()=>{const{container}=render(<TextEffectsComboCounter/>);const bonus=container.querySelector(".tfx-combo-bonus");expect(bonus).toBeTruthy();expect(bonus?.textContent).toBe("PERFECT!")});it("has proper namespaced CSS classes",()=>{const{container}=render(<TextEffectsComboCounter/>);// All classes should be namespaced with tfx-combo-
expect(container.querySelector(".tfx-combo-container")).toBeTruthy();expect(container.querySelector(".tfx-combo-main")).toBeTruthy();expect(container.querySelector(".tfx-combo-number-wrapper")).toBeTruthy();expect(container.querySelector(".tfx-combo-number-container")).toBeTruthy();expect(container.querySelector(".tfx-combo-digit")).toBeTruthy();expect(container.querySelector(".tfx-combo-particle")).toBeTruthy();expect(container.querySelector(".tfx-combo-letter")).toBeTruthy();expect(container.querySelector(".tfx-combo-hit-marker")).toBeTruthy();expect(container.querySelector(".tfx-combo-text-wrapper")).toBeTruthy();expect(container.querySelector(".tfx-combo-bonus")).toBeTruthy()});it("applies animation delay as inline style to particles",()=>{const{container}=render(<TextEffectsComboCounter finalValue={100}/>);const particles=container.querySelectorAll(".tfx-combo-particle");particles.forEach(particle=>{const style=(particle as HTMLElement).style;expect(style.animationDelay).toBeTruthy();expect(style.animationDelay).toMatch(/\d+ms/)})});it("has data-animation-id attribute",()=>{const{container}=render(<TextEffectsComboCounter/>);const element=container.querySelector("[data-animation-id=\"text-effects__combo-counter\"]");expect(element).toBeTruthy()})});describe("Edge Cases",()=>{it("handles finalValue of 1",()=>{const{container}=render(<TextEffectsComboCounter finalValue={1}/>);const particles=container.querySelectorAll(".tfx-combo-particle");expect(particles.length).toBe(1)});it("handles finalValue of 2",()=>{const{container}=render(<TextEffectsComboCounter finalValue={2}/>);const particles=container.querySelectorAll(".tfx-combo-particle");expect(particles.length).toBe(1);// Math.floor(2/2) = 1
});it("handles finalValue of 3",()=>{const{container}=render(<TextEffectsComboCounter finalValue={3}/>);const particles=container.querySelectorAll(".tfx-combo-particle");expect(particles.length).toBe(1);// Math.floor(3/2) = 1
});it("handles large finalValue",()=>{const{container}=render(<TextEffectsComboCounter finalValue={9999}maxParticles={6}/>);const particles=container.querySelectorAll(".tfx-combo-particle");expect(particles.length).toBe(6);// Capped at maxParticles
})});describe("Milestone Calculation",()=>{it("calculates evenly distributed milestones for finalValue=100",()=>{const{container}=render(<TextEffectsComboCounter finalValue={100}maxParticles={4}/>);const particles=container.querySelectorAll(".tfx-combo-particle");const values=Array.from(particles).map(p=>parseInt(p.textContent?.replace("+","")||"0"));// For 100 with 4 particles: [25, 25, 25, 25]
expect(values).toEqual([25,25,25,25])});it("calculates milestones for finalValue=10",()=>{const{container}=render(<TextEffectsComboCounter finalValue={10}maxParticles={4}/>);const particles=container.querySelectorAll(".tfx-combo-particle");const values=Array.from(particles).map(p=>parseInt(p.textContent?.replace("+","")||"0"));// Should show 4 particles with reasonable distribution
expect(particles.length).toBe(4);expect(values.reduce((a,b)=>a+b,0)).toBe(10)});it("avoids +1 spam for small numbers",()=>{const{container}=render(<TextEffectsComboCounter finalValue={5}maxParticles={4}/>);const particles=container.querySelectorAll(".tfx-combo-particle");// Should show only 2 particles to avoid +1, +1, +1, +1, +1
expect(particles.length).toBe(2);const values=Array.from(particles).map(p=>parseInt(p.textContent?.replace("+","")||"0"));values.forEach(value=>{expect(value).toBeGreaterThan(1);// Each should be meaningful
})})})});
